# Justfile to setup orbstack gg env
#
# For reference:
# https://cheatography.com/linux-china/cheat-sheets/justfile/
#
# loads envs from .env
# set dotenv-load := true

# setup/login
morning:
  echo "implement good morning stuff"

# list gg repos
repols:
	gh repo list stingerlabs --no-archived --source --limit=200 | awk '{print $1}'

# list images for repo
imagels REPO:
  aws ecr list-images \
    --repository-name gg/{{ REPO }} \
    --region us-east-2 \
    --profile cicd_GreenlightEngineer

# list gg repos sorted by last updated
sortedls:
	gh repo list stingerlabs \
		--source --no-archived --limit=200 --json="name,pushedAt" \
		| jq -r 'sort_by(.pushedAt) | reverse | .[] | .name'

# interactively select gg repos to clone
clonerepos:
  just sortedls \
  | fzf --multi --height 50% --reverse \
  | parallel gh repo clone stingerlabs/{}
# eventually we want to:
# - select repos from this list
# - clone selected repos
# - maybe setup envs for specific repos?
# - do something or other with aws, npm, java, etc.

pushpr BRANCH:
  git co -B {{ BRANCH }}
  git push -u origin {{ BRANCH }}
  gh pr create --fill --web
