# Justfile to setup orbstack gg env
#
# For reference:
# https://cheatography.com/linux-china/cheat-sheets/justfile/
#
# loads envs from .env
# set dotenv-load := true

default:
	@just --list

# offboarding
offboard LASTNAME EMAIL:
 echo "implement offboarding"
 # need to action:
 # 1) github - code: remove by github username, PR
 # 2) aws - UI - gg_root, IAM identity Center, delete user
 # 3) datadog - UI - user disable
 # 4) tailscale - UI - machine, user, code: remove email
 # 5) harness - code: remove email, PR
 # 6) snyk - UI
 # 7) jira - UI
 # 8) opsgenie - code: remove email, PR
 # 9) ansible - code: search, remove refs to slack username, PR
 # 10) postman - UI

# setup/login
morning:
	echo "implement good morning stuff"

awslogin:
	aws sso login --profile "${AWS_SSO_PROFILE:-cicd_GreenlightEngineer}"

# list gg repos
repols:
	gh repo list stingerlabs --no-archived --source --limit=200 | awk '{print $1}'

# list images for repo
imagels REPO:
	aws ecr list-images \
		--repository-name gg/{{ REPO }} \
		--region us-east-2 \
		--profile cicd_GreenlightEngineer

# list gg repos sorted by last updated
sortedls:
	gh repo list stingerlabs \
		--source --no-archived --limit=200 --json="name,pushedAt" \
		| jq -r 'sort_by(.pushedAt) | reverse | .[] | .name'

# interactively select gg repos to clone
clonerepos:
	just sortedls \
	| fzf --multi --height 50% --reverse \
	| parallel gh repo clone stingerlabs/{}
# eventually we want to:
# - select repos from this list
# - clone selected repos
# - maybe setup envs for specific repos?
# - do something or other with aws, npm, java, etc.

pushpr BRANCH:
	git co -B {{ BRANCH }}
	git push -u origin {{ BRANCH }}
	gh pr create --fill --web
