#!/usr/bin/env bash

cover() {
  t=$(mktemp)
  # go test "$COVERFLAGS" -coverprofile="$t" "$@" && go tool cover -func="$t" && unlink "$t"
  go test -coverprofile="$t" "$@" && go tool cover -func="$t" && unlink "$t"
}

cover-web() {
  t=$(mktemp)
  # go test "$COVERFLAGS" -coverprofile="$t" "$@" && go tool cover -html="$t" && unlink "$t"
  go test -coverprofile="$t" "$@" && go tool cover -html="$t" && unlink "$t"
}

stress() {
  # go test -c
  # comment above and uncomment below to enable the race builder
  go test -c -race
  PKG=$(basename $(pwd))

  while true ; do 
    export GOMAXPROCS=$[ 1 + $[ RANDOM % 128 ]]
    ./$PKG.test $@ 2>&1
  done
}
