#!/usr/bin/env sh

if [ -d "$HOME/bin" ] ; then
  PATH="$HOME/bin:$PATH"
fi

# export XDG_CONFIG_HOME=$HOME/.config

export EDITOR=nvim
export VISUAL=nvim
# export FZF_DEFAULT_COMMAND='rg --files --hidden --smart-case --glob "!.git/*"'
# export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
export FZF_DEFAULT_COMMAND='fd --type f'
export KITTY_LISTEN_ON=unix:/tmp/kitty
export NNN_FIFO=/tmp/nnn.fifo
NNN_FOLDERS="w:$HOME/vimwiki;n:$HOME/notes/wiki"
NNN_PLUGINS='o:fzopen;p:preview-tui'
export NNN_PLUG="$NNN_FOLDERS;$NNN_PLUGINS"
export NNN_OPENER="$HOME/.config/nnn/plugins/nuke"
export ERL_AFLAGS="-kernel shell_history enabled"
export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"

export CLICOLOR=1
export LSCOLORS=ExFxCxDxBxegedabagacad

export GOBIN="$HOME/.local/bin"
export ASDF_GOLANG_MOD_VERSION_ENABLED=true

if [ -e "$HOME/.env.local" ] ; then
  . "$HOME/.env.local"
fi
export PATH="$HOME/.local/bin:$PATH"


. $HOME/.asdf/asdf.sh
