-- bootstrap
-- if package.loaded["lazy"] then return {} end
--
-- local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
-- if not vim.loop.fs_stat(lazypath) then
--   vim.fn.system({
--     "git",
--     "clone",
--     "--filter=blob:none",
--     "--single-branch",
--     "https://github.com/folke/lazy.nvim.git",
--     lazypath,
--   })
-- end
-- vim.opt.runtimepath:prepend(lazypath)
--
-- -- initalize lazy and load plugins
-- require("lazy").setup("plugs", {
-- 	defaults = {
-- 		lazy = false, -- should plugins be lazy-loaded?
-- 	},
-- 	dev = {
-- 		-- directory where you store your local plugin projects
-- 		-- path = vim.fn.stdpath("config") .. "/lua/my",
-- 		---@type string[] plugins that match these patterns will use your local versions instead of being fetched from GitHub
-- 		-- patterns = {"philshaughnes"},
-- 	},
-- 	install = {
-- 		-- try to load one of these colorschemes when starting an installation during startup
-- 		colorscheme = { "doom-one" },
-- 	},
-- 	-- these are probably all defaults
-- 	ui = {
-- 		custom_keys = {
-- 			-- you can define custom key maps here.
-- 			-- To disable one of the defaults, set it to false
--
-- 			-- open lazygit log
-- 			["<localleader>l"] = function(plugin)
-- 				require("lazy.util").open_cmd({ "lazygit", "log" }, {
-- 					cwd = plugin.dir,
-- 					terminal = true,
-- 					close_on_exit = true,
-- 					enter = true,
-- 				})
-- 			end,
--
-- 			-- open a terminal for the plugin dir
-- 			["<localleader>t"] = function(plugin)
-- 				require("lazy.util").open_cmd({ vim.go.shell }, {
-- 					cwd = plugin.dir,
-- 					terminal = true,
-- 					close_on_exit = true,
-- 					enter = true,
-- 				})
-- 			end,
-- 		},
-- 	},
-- 	diff = {
-- 		-- diff command <d> can be one of:
-- 		-- * browser: opens the github compare view. Note that this is always mapped to <K> as well,
-- 		--   so you can have a different command for diff <d>
-- 		-- * git: will run git diff and open a buffer with filetype git
-- 		-- * terminal_git: will open a pseudo terminal with git diff
-- 		-- * diffview.nvim: will open Diffview to show the diff
-- 		cmd = "git",
-- 	},
-- 	performance = {
-- 		rtp = {
-- 			---@type string[] list any plugins you want to disable here
-- 			disabled_plugins = {
-- 				"gzip",
-- 				"matchit",
-- 				"matchparen",
-- 				"netrwPlugin",
-- 				"tarPlugin",
-- 				"tohtml",
-- 				-- "tutor",
-- 				"zipPlugin",
-- 			},
-- 		},
-- 	},
-- })
return {}
-- PERSONAL BUT USEFUL (12)
-- ● arrow.nvim 8.49ms  ; - primary buffer set
-- ● Comment.nvim 1.13ms  start - toggle comments
-- ● fzf-lua 14.56ms 󰢱 fzf-lua  keys - fuzzy find all the things
-- ● indent-o-matic 0.6ms  start - auto setup indent
-- ● kanagawa.nvim 3.2ms  start - colorscheme
-- ● lazy.nvim 5.38ms  init.lua - package manager
-- ● nnn.nvim 18.41ms  NnnPicker - file browser/manager
-- ● nvim-bqf 1.02ms  qf - make qf list better
-- ● nvim-snippy 3.4ms  nvim-cmp - snippets
-- ● nvim-surround 1.88ms  start - add/remove surrounding stuff
-- ● vim-niceblock 0.71ms  InsertEnter - add stuff in block mode
-- ○ obsidian.nvim  markdown  - notes
-- GIT STUFF (5)
-- ○ neogit  Neogit
-- ● gitsigns.nvim 0.99ms  VeryLazy
-- ○ gitlinker.nvim
-- ○ diffview.nvim  DiffviewFileHistory  DiffviewOpen  neogit
-- ○ plenary.nvim  gitlinker.nvim  neogit  diffview.nvim
-- NICE TO HAVE (8)
-- ● troublesum.nvim 2.1ms  BufWritePost - show diagnostics in corner
-- ● which-key.nvim 0.24ms 󰢱 which-key  keys - key help/hints
-- ○ treesj  TSJToggle  - reverse J
-- ● cinnamon.nvim 0.73ms  VeryLazy - smooth scroll
-- ● nvim-autopairs 3ms  InsertEnter - auto parents etc
-- ○ nvim-align  Align  - align stuff
-- ○ venn.nvim  VBox - add boxes and diagrams to notes
-- ● tabout.nvim 3.62ms  InsertEnter - tab to get out of parens, etc
-- MAYBE NOT NEEDED (7)
-- ○ tokyonight.nvim - alternative colorscheme
-- ○ cellular-automaton.nvim  CellularAutomaton - cool animation
-- ○ vimwiki  VimwikiIndex - old notes
-- ○ nvim-osc52 - should enable copy via ssh, but haven't got to work
-- ○ mini.clue - whichkey alternative
-- ○ lualine.nvim - pretty line
-- ○ doom-one.nvim - another colorscheme
-- IDE STUFF (10) - format, lint, lsp, treesitter
-- ● conform.nvim 2.67ms  BufWritePre
-- ● nvim-lint 3.72ms  BufWritePre
-- ● fidget.nvim 4.8ms  start
-- ● lsp-timeout.nvim 0.35ms  start
-- ● lspkind-nvim 0.09ms  nvim-cmp
-- ● mason.nvim 2.01ms  start
-- ● nvim-treesitter 6.1ms 󰢱 nvim-treesitter.query  nvim-treesitter-endwise
-- ● nvim-web-devicons 0.6ms 󰢱 nvim-web-devicons  arrow.nvim
-- ● nvim-lspconfig 7.02ms  start
-- ○ nvim-code-action-menu  CodeActionMenu
-- COMPLETION (5)
-- ● nvim-cmp 27.23ms  InsertEnter
-- ● cmp-cmdline 1.86ms  nvim-cmp
-- ● cmp-nvim-lsp 0.05ms 󰢱 cmp_nvim_lsp  nvim-lspconfig
-- ● cmp-path 16.61ms  nvim-cmp
-- ● cmp-snippy 1.46ms  nvim-cmp
--
